[package]
name = "krossbar-bus-common"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"
bytes = "1.1"
bson = "2.3"
log = "0.4"
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1.19", features = ["io-util", "net", "sync"] }

karo-common-messages = { git = "https://github.com/krossbar-platform/krossbar-common.git" }
