#!/bin/bash

# Replace autogenerated README symbol links with corresponding links to 'docs.rs'

WORKING_DIR=$1

# Generate README.md from crate docs
run_cargo_readme() {
    if [ -f "${WORKING_DIR}/src/main.rs" ]
    then
        cargo readme -i "${WORKING_DIR}/src/main.rs" > "${WORKING_DIR}/README.md"
    else
        cargo readme -i "${WORKING_DIR}/src/lib.rs" > "${WORKING_DIR}/README.md"
    fi
}

# Get package name from Cargo.toml
get_package_name() {
    echo $(sed -rn 's/^name = "(.+)"$/\1/p' "${WORKING_DIR}/Cargo.toml" | head -1)
}

# Get docs HTML, which is used to find docs.rs links for all symbols in the README
get_docs_html() {
    local UNDER_CRATE_NAME="${1//\-/_}"

    if [ -d "${WORKING_DIR}/target/" ]
    then
        cat "${WORKING_DIR}/target/doc/${UNDER_CRATE_NAME}/index.html"
    else
        if [ ! -d "${WORKING_DIR}/../target/" ]; then
            echo "Failed to find target dir"
            exit 1
        fi

        cat "${WORKING_DIR}/../target/doc/${UNDER_CRATE_NAME}/index.html"
    fi
}

# Make absolute links for both: crate internal links and dependencies links
expand_link() {
    local STRING=$1
    local PACKAGE_NAME=$2

    if [[ "${STRING}" == ..* ]]
    then
        local PACKAGE_NAME=$(echo "${STRING}" | sed -rn "s/\.\.\/(\w+)\/.*/\1/p")
        local TAIL=${STRING/\.\.\/${PACKAGE_NAME}\//}
        echo "https://docs.rs/${PACKAGE_NAME//_/\-}/latest/${PACKAGE_NAME}/${TAIL}"
    else
        echo "https://docs.rs/${PACKAGE_NAME}/latest/${PACKAGE_NAME//\-/_}/${STRING}"
    fi
}

# Replace symbols links with absolute links in the README
replace_symbols_with_doc_links() {
    # Find all crate symbols links
    local SYMBOLS=$(sed -rn 's/[^\[]*\[([[:alnum:]_:]+)\][^\(].*/\1/p' "${WORKING_DIR}/README.md" | sort -u)
    local DOCS_HTML="$1"

    for SYMBOL in ${SYMBOLS}
    do
        # Get a URL for a symbol from the local docs
        local URL=$(echo "${DOCS_HTML}" | sed -rn "s/.*<a href=\"(\S+)\".*>${SYMBOL}<\/a>.*/\1/p" | head -1)
        local ABSOLUTE_LINK=$(expand_link "${URL}" "$2")

        # Replace symbol link woth rear docs links
        sed -ri "s|\[${SYMBOL}\]|[${SYMBOL}](${ABSOLUTE_LINK})|g" "${WORKING_DIR}/README.md"
    done
}

if [ "$#" -ne 1 ]
then
    echo "Pass working directory"
    exit 1
fi

# Generate README.md
run_cargo_readme
# Generate crate docs
cargo doc

# Get package name from Cargo.md
PACKAGE_NAME=$(get_package_name)
echo "Package: ${PACKAGE_NAME}"

# Read docs HTML
DOCS_HTML=$(get_docs_html "${PACKAGE_NAME}")
# Replace carte links with absolute links in the README
replace_symbols_with_doc_links "${DOCS_HTML}" "${PACKAGE_NAME}"